# Site settings
  title: Filosofía Antigüa, los orígenes de la Metempsicosis
author:
  name: Paulina Michelle Mendoza
  email: 00paumendoza@gmail.com
description: Sitio para el curso de Humanidades Digiates impartido por Ernesto Priani, en el que se expondrán actividades, reflexiones y discusiones acerca de temas relacionados con las humanidades digitales.
# Build settings
theme: jekyll-theme-slate
